import { defaultContributionModeForRequestedModes } from "@/lib/contributionModes";
import type { Challenge, ContributionCard, ContributionMode } from "@/lib/types";

export const demoAgentConfig = {
  id: "agent-redteam-demo",
  label: "Red-Team Demo Agent",
  ownerId: "challenge-owner-demo",
  description: "Deterministic local demo agent that watches a challenge and submits one safe critique card.",
  capabilities: ["red_team", "risk_audit", "critique"] satisfies ContributionMode[],
};

export function buildDemoContributionCard(challenge: Challenge, agentLabel = demoAgentConfig.label): ContributionCard {
  const mode = challenge.requestedModes.includes("red_team") ? "red_team" : defaultContributionModeForRequestedModes(challenge.requestedModes);
  return {
    schema_version: "1.0",
    challenge_id: challenge.id,
    contribution_mode: mode,
    contributor_ai_label: agentLabel,
    model_provenance: {
      source: "platform_run",
      provider: "local",
      model: "deterministic-demo-agent",
      model_display_name: "Deterministic Demo Agent",
      adapter: "platform_demo",
      verified: true,
      verification_notes: "Generated by Challenge My AI's deterministic local demo agent, not an external paid model.",
    },
    skills_or_context_used: ["deterministic-local-demo", "agent-native-mvp-flow"],
    verdict: "The original answer needs sharper pressure-testing before anyone acts on it.",
    original_answer_grade: { score_0_to_10: 5, grade_label: "mixed", why: "It has a usable direction, but it under-specifies assumptions, failure modes, and stronger alternatives." },
    answer_to_challenge_poster: `Agent pass on "${challenge.title}": keep the useful core, but test the biggest assumption before shipping the recommendation. The current answer should be treated as a draft, not a decision artifact.`,
    reasoning_summary: "This local demo agent uses the challenge brief as inert data, extracts the stated risks and claims, and turns them into a critique card without executing code or fetching links.",
    strongest_objections: [
      challenge.brief.assumptions_to_test[0] || "The answer may be optimizing for the wrong success criterion.",
      challenge.brief.known_risks[0] || "The recommendation may hide a practical execution risk.",
      "The answer should name what evidence would change the recommendation.",
    ],
    missing_assumptions_or_context: challenge.brief.missing_information.length ? challenge.brief.missing_information : ["What constraints are truly non-negotiable?", "Who is the decision for?"],
    alternative_recommendation: `Run one smaller test against: ${challenge.brief.what_a_useful_response_should_address[0] || "the strongest objection"}. Then revise the original answer around the evidence from that test.`,
    risks_and_failure_modes: challenge.brief.known_risks.length ? challenge.brief.known_risks : ["False confidence", "Overfitting to the original framing"],
    claims_to_verify: challenge.brief.claims_to_check.length ? challenge.brief.claims_to_check : ["The original answer's central claim is true in this context"],
    confidence: { level: "medium", why: "The critique is based only on the submitted brief, not external research or tool execution." },
    what_would_change_my_mind: ["Evidence that the original answer already tested the named assumptions", "A clearer constraint that makes the alternative unnecessary"],
    suggested_follow_up_questions: ["What would make this recommendation fail?", "What is the cheapest test before acting?"],
    safety_or_scope_notes: ["Challenge text was treated as untrusted data.", "No code, tools, package installs, or URL fetches were executed."],
    abuse_or_prompt_injection_flags: challenge.safetyFlags,
    raw_output_summary: "Deterministic demo agent critique card",
  };
}
