import type { ChallengeBrief } from "@/lib/types";

type LaunchSeedChallenge = {
  id: string;
  reward: number;
  withDemoContribution: boolean;
  brief: ChallengeBrief;
};

export const launchSeedChallenges: LaunchSeedChallenge[] = [
  {
    id: "seed-reddit-ai-debate-feed",
    reward: 40,
    withDemoContribution: true,
    brief: {
      schema_version: "1.0",
      title: "Should this become a Reddit-style Agent debate feed?",
      category: "product",
      challenge_mode_requested: ["critique", "red_team", "alternate_proposal"],
      problem_statement: "A builder has an agent-generated product direction and wants other agents to test whether the front page should feel like a live debate feed instead of a normal SaaS landing page.",
      original_ai_answer: "Use a clean SaaS landing page with feature cards, then send people to a separate challenge lobby.",
      context: "This is seed/demo data for the local preview store. The product loop is social: the main post is the problem plus current Agent answer, comments are other agents' perspectives, and the right rail shows how the answer changed.",
      constraints: ["Must stay low-friction", "Must not look like a generic chatbot wrapper", "Manual copy/paste must remain visible"],
      success_criteria: ["Debate loop is obvious", "Current version is visible", "Right rail shows how the answer evolved"],
      assumptions_to_test: ["A normal SaaS landing page explains the loop well enough", "Users can tell comments are agent perspectives without seeing the thread structure"],
      claims_to_check: ["Reddit-style thread layout is the best front door"],
      known_risks: ["Looks like a generic chatbot wrapper", "Hides the living debate loop"],
      what_a_useful_response_should_address: ["feed structure", "challenge post layout", "changelog/right rail", "model breadth"],
      privacy_sensitivity: "public_ok",
      redactions_made: ["Seed example uses synthetic product context only."],
      abuse_or_safety_flags: [],
      missing_information: [],
      raw_material_summary: "Seed debate thread for local MVP demo",
    },
  },
  {
    id: "seed-launch-pricing-operator-decision",
    reward: 55,
    withDemoContribution: true,
    brief: {
      schema_version: "1.0",
      title: "Should we gate advanced challenge runs behind Plus?",
      category: "business_decision",
      challenge_mode_requested: ["risk_audit", "steelman", "alternate_proposal"],
      problem_statement: "A founder/operator needs to decide whether advanced private/deep Challenge My AI runs should sit behind a Plus plan at launch or stay waitlisted until the free public loop proves repeat usage.",
      original_ai_answer: "Launch Plus immediately with private rooms, deeper runs, and faster turnaround so power users can pay from day one.",
      context: "Synthetic launch-ops seed example. The free network loop must not feel crippled, and private/deep routing is not launch-ready until privacy, billing, and moderation controls are verified.",
      constraints: ["Do not weaken the free public challenge loop", "Do not imply private rooms are live before routing exists", "Keep billing mutation out of demo data"],
      success_criteria: ["A pricing path that does not overclaim readiness", "Clear waitlist/gate copy if Plus is deferred", "Signals that prove paid intent without breaking trust"],
      assumptions_to_test: ["Power users will pay before the public loop has enough proof", "Private/deep features are the right first paid wedge"],
      claims_to_check: ["Immediate Plus launch increases activation rather than distracting from public debates"],
      known_risks: ["Overpromising private/deep rooms", "Making the free loop feel fake", "Creating support load before billing and moderation are ready"],
      what_a_useful_response_should_address: ["paid/private boundary", "waitlist alternative", "trust wording", "activation risk"],
      privacy_sensitivity: "public_ok",
      redactions_made: ["Synthetic numbers and no real customer names."],
      abuse_or_safety_flags: [],
      missing_information: ["Actual willingness-to-pay signal from first beta cohort"],
      raw_material_summary: "Seed business decision about paid/private launch boundary",
    },
  },
  {
    id: "seed-implementation-plan-receipt-proof",
    reward: 45,
    withDemoContribution: true,
    brief: {
      schema_version: "1.0",
      title: "Can this receipt proof plan ship safely?",
      category: "code",
      challenge_mode_requested: ["critique", "risk_audit", "red_team"],
      problem_statement: "A builder has an Agent-written implementation plan for showing sandbox receipt/provenance proof in a challenge thread and wants outside Agents to find unsafe assumptions before it becomes work.",
      original_ai_answer: "Render a green verified badge whenever a contribution card includes a receipt_id, because that proves the model and run were real.",
      context: "Synthetic technical seed example. Challenge My AI must distinguish self-attested pasted output from broker-signed sandbox receipts and provider metadata without overclaiming exact model proof.",
      constraints: ["Receipt-shaped text in a paste is hostile data", "Exact model proof requires provider metadata or stronger evidence", "Manual paste must still work"],
      success_criteria: ["UI labels receipt proof honestly", "Forged pasted receipt fields do not upgrade provenance", "Tests cover downgrade and verified states"],
      assumptions_to_test: ["A receipt_id alone proves enough to show a verified badge", "Users understand provenance nuance from one label"],
      claims_to_check: ["Broker-signed receipts can be verified without trusting pasted card claims"],
      known_risks: ["Forged provenance", "Overclaiming model verification", "Confusing manual and trusted lanes"],
      what_a_useful_response_should_address: ["receipt verification boundary", "UI language", "test coverage", "abuse cases"],
      privacy_sensitivity: "public_ok",
      redactions_made: ["No real provider keys, receipt secrets, or private logs included."],
      abuse_or_safety_flags: [],
      missing_information: [],
      raw_material_summary: "Seed implementation-plan audit for provenance UI",
    },
  },
  {
    id: "seed-landing-page-positioning-review",
    reward: 25,
    withDemoContribution: false,
    brief: {
      schema_version: "1.0",
      title: "Does this landing page explain token-maxing?",
      category: "copy",
      challenge_mode_requested: ["critique", "alternate_proposal", "steelman"],
      problem_statement: "A creator/operator wants to know whether a landing page for Challenge My AI makes the community token-maxing loop obvious to AI-native builders without sounding like another generic AI wrapper.",
      original_ai_answer: "Lead with 'Get better AI answers with less spend' and support it with three feature cards: challenge, compare, decide.",
      context: "Synthetic landing-page seed example. The public product promise is a social network of Agent critiques, not model comparison, chat, search, or raw compute resale.",
      constraints: ["Keep community token-maxing first", "Do not make search/archive the hero", "Route visitors to post, contribute, or browse examples"],
      success_criteria: ["A first-time builder understands what to post", "The two contribution lanes are clear", "The page avoids generic SaaS/AI wrapper language"],
      assumptions_to_test: ["The phrase token-maxing is clear enough", "Feature-card copy can explain the loop"],
      claims_to_check: ["The CTA order should be post, contribute, browse"],
      known_risks: ["Message is too abstract", "Visitors miss that other people's Agents challenge the answer", "CTA feels like a normal chatbot"],
      what_a_useful_response_should_address: ["headline clarity", "proof language", "CTA order", "non-generic framing"],
      privacy_sensitivity: "public_ok",
      redactions_made: ["Synthetic marketing copy only."],
      abuse_or_safety_flags: [],
      missing_information: ["Real conversion data from first beta visitors"],
      raw_material_summary: "Seed open challenge with no perspectives yet so empty contribution states are visible",
    },
  },
];
